### ISSUE TITLE
Usage of `file_get_contents` causes PHP warning when `allow_url_fopen` is disabled in PHP.ini

### ISSUE THREAD

**Issue by thomasplevy** [gocodebox/lifterlms-helper#8]
This error can be seen when viewing the changelog when popping a thickbox from the plugins screen for an add-on with a pending upgrade.

![_78357_upgrade_plugin_-_new_registration_subscribers_-_chicca_pancaldi](https://user-images.githubusercontent.com/1290739/52750706-dae21300-2fa1-11e9-86ab-4e2d452b5eb8.jpg)

**Comment by eri-trabiccolo** [comment]
@thomasplevy 
should we use cURL I think and fall back on `file_get_contents($someremoteURL)` only if cURL is not available?
`allow_url_fopen` set to `1` it's a security risk (have to find a prove I know, but I remember I talked about this recently with a "friend of mine" who runs a small hosting provider in Italy - he's a good sysadmin).

HS-115415

**Comment by thomasplevy** [comment]
We should actually probably switch to `wp_remote_get()`

**Comment by eri-trabiccolo** [comment]
yeah, better! :D

**Comment by thomasplevy** [comment]
Resolved in 3.1.0
